model_type: t5-base
epochs: 20
max_len: 200
model_save_name: t5-base.pt
datasets_path: data/processed
metrics_folder: metrics
metrics_file: base_p_fold_tf_metrics.csv
oversampling: false
clear_models_dir: true
early_stopping: true
seed: 42

sec_label: "true"
nonsec_label: "false"

validation: p-validation
# cross-validation: stratified cross-validation, test_datasets are ignored
# p-validation: training on one projects and testing on others 
datasets_config_path: configs/datasets_config.yaml
