model_type: t5-small
epochs: 15
max_len: 200
model_save_name: t5-small.pt
datasets_path: data/processed
metrics_file: small_cross_os_metrics.csv
oversampling: true
clear_models_dir: true
early_stopping: true
seed: 42

sec_label: "sec"
nonsec_label: "nonsec"

validation: cross-validation
# cross-validation: stratified cross-validation, test_datasets are ignored
# p-validation: training on one projects and testing on others 
datasets_config_path: configs/datasets_config.yaml
